//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions
    {
        public int id { get; set; }
        public int User_id { get; set; }
        public int Type_id { get; set; }
    
        public virtual Subscription_type Subscription_type { get; set; }
        public virtual Users Users { get; set; }
    }
}
